name: sombra_testes
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  file_picker: ^8.0.3
  flutter_bloc: ^8.1.3
  connectivity_plus: ^6.0.3
  flutter_local_notifications: ^17.1.2
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.2.6
  cloud_firestore: ^4.9.1
  google_maps_flutter: ^2.5.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  dio: ^5.3.2
  location: ^6.0.2
  permission_handler: ^11.3.1
  google_maps_flutter_web: ^0.5.4+2
  flutter_image_compress: ^2.3.0
  flutter_google_places_sdk: ^0.3.7
  flutter_polyline_points: ^2.0.0
  google_maps_directions: ^0.0.4
  google_routes_flutter: ^1.0.0+1
  auto_size_text: ^3.0.0
  background_location_tracker: ^1.4.1
  shared_preferences: ^2.2.2
  uuid: ^4.4.0
  validadores: ^1.0.9
  image_picker: ^1.0.7
  wakelock_plus: ^1.1.3
  firebase_database: ^10.3.5
  responsive_framework: ^1.1.1
  intl: ^0.18.1
  pdf: ^3.10.6
  path_provider: ^2.1.1
  google_static_maps_controller: ^1.0.0
  cloud_functions: ^4.5.6
  data_table_2: ^2.5.9
  cached_network_image: ^3.3.0
  camera: ^0.11.0
  path: ^1.8.3
  image: ^4.1.3
  image_gallery_saver: ^2.0.3
  diacritic: ^0.1.5
  photo_view: ^0.15.0
  flutter_native_splash: ^2.3.9
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.0.0
  flutter_multi_formatter: ^2.12.3
  tuple: ^2.0.2
  latlong2: ^0.9.0
  internet_connection_checker: ^1.0.0+1
  sqflite: ^2.3.0
  workmanager: ^0.5.2
  sidebarx: ^0.17.1
  dashboard: ^0.0.4
  responsive_grid: ^2.4.4
  stepper_a: ^1.3.0
  panara_dialogs: ^0.1.4
  flutter_swipe_button: ^2.1.1+1
  hawk_fab_menu: ^1.2.0
  brasil_fields: ^1.14.1
  google_fonts: ^6.1.0
  persistent_bottom_nav_bar: ^5.0.2
  icons_plus: ^5.0.0
  swipe_refresh: ^1.0.2
  gradient_ui: ^1.1.0
  dynamic_tabbar: ^1.0.5
  async: ^2.11.0
  flutter_audio_waveforms: ^1.2.1+8
  record: ^5.0.4
  audioplayers: ^6.0.0
  image_card: ^0.0.4
  audio_waveforms: ^1.0.5
  timeago: ^3.6.1
  grouped_list: ^5.1.2
  emoji_picker_flutter: ^1.6.4
  any_link_preview: ^3.0.2
  styled_text: ^8.1.0
  timezone: ^0.9.2
  flutter_localization: ^0.2.0
  fl_chart: ^0.68.0
  graphic: ^2.2.1
  audioplayers_web: ^5.0.0
  flutter_quill: ^9.3.11
  provider: ^6.1.2
  animations: ^2.0.11
  printing: ^5.12.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/escudo.png
    - assets/images/fotoDePerfilNull.jpg
    - assets/images/file_searching-pana.png
    - assets/images/car-pana.png
    - assets/images/warning-pana.png
    - assets/images/attention-pana.png
    - assets/images/confirm.png
    - assets/images/stop-pana.png
    - assets/images/missao-pana.png
    - assets/images/logo-null.jpg
    - assets/images/facebook_icon.png
    - assets/images/google_icon.png
    - assets/images/missionIcon.png
    - assets/images/empresas.png
    - assets/images/users.jpg
    - assets/images/relatorios.jpeg
    - assets/images/agentes.jpeg
    - assets/sounds/notification-message-incoming.mp3
    - assets/images/notificacao.jpeg

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  remove_alpha_ios: true
  adaptive_icon_background: "#000000"
  android: true
  ios: true
  image_path: "assets/images/escudo.png"

flutter_native_splash:
    image: "assets/images/escudo.png"
    android: true
    ios: true
    color: "#000000"


